### ISSUE TITLE
[PE-D] Inconsistency in command feature formatting for `Format`

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2103-F11-4/tp#100]
These two features uses an integer value in their respective commands. The description of how these integer values are used are identical. But the first use `<Integer>` and the latter uses `INTEGER`.

![image.png](https://raw.githubusercontent.com/junrong98/ped/main/files/89bfb2c8-ffc7-4689-95ab-7d77f2815df5.png)

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: junrong98/ped#5

**Comment by putaojuice** [comment]
@castryl please help to vet through the documentations

**Comment by ivorcmx** [comment]
Fixed
