### ISSUE TITLE
[PE-D] UG improper formatting

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2103-F11-4/tp#103]
First line of the user guide seems to be improperly formatted.

![Picture10.png](https://raw.githubusercontent.com/medajet/ped/main/files/9cec4c3c-fa39-4929-8d9a-6a97c3e5f5db.png)

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: medajet/ped#9

**Comment by ivorcmx** [comment]
Fixed
