### ISSUE TITLE
[PE-D] Missing hyperlinks for table of contents

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2103-F11-4/tp#105]
Table of contents do not have hyperlinks to the relevant sections.

![Picture11.png](https://raw.githubusercontent.com/medajet/ped/main/files/118b3035-cea3-4e89-b437-c4b415ef5bb9.png)

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: medajet/ped#10

**Comment by ivorcmx** [comment]
Fixed
