### ISSUE TITLE
[PE-D] Find tasks - mismatch between actual behavior and UG

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2103-F11-4/tp#108]
In the UG, it is mentioned that only full keyword will be matched
![image.png](https://raw.githubusercontent.com/yunbinmo/ped/main/files/a5aeb2f9-2406-4689-bef0-c39b00a2aaff.png)

However, using the first letter of a word to search will also succeed, for example, 'b' will matches all tasks with words starting with letter b
![image.png](https://raw.githubusercontent.com/yunbinmo/ped/main/files/90348852-5f5f-462b-9e1f-b67485d304f2.png)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: yunbinmo/ped#3

**Comment by putaojuice** [comment]
@yumengtan you solved this already right?

**Comment by ivorcmx** [comment]
@yumengtan would appreciate if you can link your PR to this issue! 💯

**Comment by yumengtan** [comment]
@putaojuice @ivorcmx linked to pr! 🙈
