### ISSUE TITLE
[PE-D] "updt" command has incorrect format in UG

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2103-F11-4/tp#109]
For the updt command, both fields are listed as optional even though at least 1 is mandatory.

![Picture14.png](https://raw.githubusercontent.com/medajet/ped/main/files/bce0f5c7-9c4c-499c-a1ff-c2d946008a39.png)

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: medajet/ped#12

**Comment by ivorcmx** [comment]
Fixed
