### ISSUE TITLE
[PE-D] Find person command is not mentioned in the UG 

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2103-F11-4/tp#115]
![image.png](https://raw.githubusercontent.com/yunbinmo/ped/main/files/fae7f8cd-4ee7-409d-a4c3-a0897be99927.png)
Command for finding person by name is not recorded

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: yunbinmo/ped#5

**Comment by ivorcmx** [comment]
Fixed
