### ISSUE TITLE
[PE-D] "viewt" command can take extra arguments

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2103-F11-4/tp#119]
"viewt" command can take additional arguments and function correctly, e.g. "viewt aa"

![image.png](https://raw.githubusercontent.com/medajet/ped/main/files/b9564393-eaf4-4459-8f7f-dbd9e5a03f5a.png)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: medajet/ped#15

**Comment by ivorcmx** [comment]
Added in the UG that extra parameters given in such commands will be ignored
