### ISSUE TITLE
[PE-D] "addt" allows adding of duplicate tasks

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2103-F11-4/tp#126]
"addt" allows adding of duplicate tasks with the exact name and deadline.

![image.png](https://raw.githubusercontent.com/medajet/ped/main/files/541ec221-9e08-42b6-a333-8b61d1a0349d.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: medajet/ped#16

**Comment by putaojuice** [comment]
Many modern task tracker does not prevent user from adding the exact same task, thus we decided to go with what most apps out there is doing. It is up to the user how he wants to manage the task.

**Comment by ivorcmx** [comment]
Agreed. Added in the UG that duplicate tasks WILL be allowed.
