### ISSUE TITLE
[PE-D] Table of content in UG is not clickable 

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2103-F11-4/tp#127]
![Screenshot 2022-04-01 at 3.04.43 PM.png](https://raw.githubusercontent.com/AD-NAP/ped/main/files/b9536bea-b40b-4ab0-9230-72457d7c8832.png)

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: AD-NAP/ped#9

**Comment by ivorcmx** [comment]
Fixed
