### ISSUE TITLE
Plan The Next Iteration (v1.2)

### ISSUE THREAD

**Issue by putaojuice** [AY2122S2-CS2103-F11-4/tp#5]
**Plan the next iteration**. As you know, you should follow the breadth-first iterative process. Therefore, first you must decide what functionalities should be in the product if you had only two weeks to implement it. You have done that already when you chose user stories for v1.2, translated that to features, and even drafted the UG based on those features. You can tweak that plan further at this point if you wish, given that you now have some idea of how fast the team can work when using the prescribed workflow.
- **Aim to produce a working** [MVP](https://en.wikipedia.org/wiki/Minimum_viable_product) at the end of this iteration even if the functionalities are not polished (polishing can be done in a later iteration).
- **[Recommended, Optional] Break the iteration into two increments** i.e., aim to produce an even simpler but working version after one week.
- **Avoid depth-first implementations:** "I'll do the back-end part of feature X in this iteration" is not acceptable as that is not in the spirit of breadth-first iterative process. Remember, we are pretending this to be the last iteration; why would you implement the back-end part of a feature in the last iteration?
It is OK to add simpler versions of bigger features, but not OK to add partial features that can't be used yet.

**Divide the work among the team members** i.e., the work required for the current iteration.

**Reflect the above plan in the issue tracker** by assigning the corresponding issues (create new issues if necessary) to yourself and to the corresponding milestone. For example, the user story pertaining to the increment show a place holder for photo, showing a generic default image should be assigned to Jake and to milestone v1.2. **If you split the iteration into two smaller iterations** of one-week each (recommended), name the first one v1.2 and the second one v1.2b so that the dashboard can track them accurately. The reason for naming the earlier milestone as v1.2 is so that even if you fail to finish the second one, you can still get credit for reaching v1.2 (which is the milestone tracked by grading scripts) -- think of the first iteration as minimal deliverables for v1.2 and the second one as containing do-if-there-is-time improvements.

**Comment by ivorcmx** [comment]
Implement following commands:

add t
del t <integer>
find t <String>
view t

**Comment by putaojuice** [comment]
We will be implementing these 4 commands that we deemed the must have features to our product first. These features will print out the output as text on the AB3 application as of now. We will then create a UI for either v1.2b or 1.3. Our rationale is to get the features to work correctly first then improve it as we continuously grow and improve the features.

In v1.2 we will not focus on storing/loading the data.
