### ISSUE TITLE
Conduct internal SUT

### ISSUE THREAD

**Issue by putaojuice** [AY2122S2-CS2103-F11-4/tp#72]
Perform testings for the task list features, report any bug found.

**Comment by putaojuice** [comment]
### 1. Unexpected format
`addt` works if there isno whitespace between tokens. Might not be a good idea. Potentially fix it by checking if there is any token `d/` or `t/` within the description itself will be a good idea. 

Below is an example that will allow user to add task:

`addt d/DUMMYd/DUMMYt/01/01/2022`

**Comment by yumengtan** [comment]
Might not be a good idea for duplicate tasks to be allowed in the task list? 
Below is an example:
![image](https://user-images.githubusercontent.com/77229521/160974754-fcc7c2ff-24bc-45a4-881e-5803b51ea701.png)
