### ISSUE TITLE
[PE-D] Invalid date accepted as input for `addt`

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2103-F11-4/tp#86]
- 30/02/2020 is not a valid date for the month of February
- 29/02/2020 is not a valid date for the year 2022.

Steps to reproduce:
1) `addt d/test task t/30/02/2020`

2) `addt d/test task t/29/02/2022`

![image.png](https://raw.githubusercontent.com/junrong98/ped/main/files/ad33d1ff-2808-4359-9adf-52d6dce90d60.png)

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: junrong98/ped#1

**Comment by putaojuice** [comment]
Fix this asap
