### ISSUE TITLE
[PE-D] Cannot "add" person with the same name

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2103-F11-4/tp#87]
Not able to add a person with the same name as an existing person in the address book, even though it’s possible for people to have the same name.

![Picture1.png](https://raw.githubusercontent.com/medajet/ped/main/files/336481ed-3cff-4ad6-8918-d2f6ac136914.png)

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: medajet/ped#1

**Comment by putaojuice** [comment]
This is intended in AB3's code base. Having same name in address book will confuse the user and in reality most of the time when we know people with same name, we will try to come up with alternative name to distinguish them also. Therefore no modification needed in our opinion
