### ISSUE TITLE
[PE-D] Unable to execute the examples in Quick Start in UG 

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2103-F11-4/tp#92]
Someone who is following the Quick Start step-by-step, would not be able to try out the example command of `delt 3` as following the steps only ends up with 2 task in the list. Maybe provide with more sample tasks. Or change it to `delt 2`

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: AD-NAP/ped#2

**Comment by ivorcmx** [comment]
Fixed
