### ISSUE TITLE
[PE-D] "addt" allows t/ inside d/ tag

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2103-F11-4/tp#94]
When doing addt, it’s possible to add a t/ inside the description and it will still go through successfully.

![Picture5.png](https://raw.githubusercontent.com/medajet/ped/main/files/eeada61a-c68a-419d-9147-f7021de9d3fb.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: medajet/ped#4

**Comment by putaojuice** [comment]
Fix the tokenizer logic, refuse entry if there exist any token in the description field
