### ISSUE TITLE
[PE-D] "clear" command does not clear tasks

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2103-F11-4/tp#98]
“clear” command doesn’t clear tasks, even though UG states that it clears all entries.

![Picture8.png](https://raw.githubusercontent.com/medajet/ped/main/files/87bc80ad-89e1-42dc-b06b-917d3eddb537.png)

Relevant excerpt from UG:

![image.png](https://raw.githubusercontent.com/medajet/ped/main/files/bbd4421a-a669-4626-b693-8c830f231c30.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: medajet/ped#7

**Comment by putaojuice** [comment]
not meant to clear tasks.

**Comment by yumengtan** [comment]
Update UG to reflect that clear only clears contact entries

**Comment by ivorcmx** [comment]
Fixed
